---
- name: test connection to servers
  hosts: all
  tasks:
    - name: install httpd
      become: yes
      ansible.builtin.package:
        name: httpd
        state: present

    - name: start and enable httpd service
      become: yes
      ansible.builtin.service:
        name: httpd
        state: restarted
        enabled: true

- name: copy files to jenkins
  hosts: jenkins
  tasks:
    - name: copy html page
      become: yes
      ansible.builtin.copy:
        src: resources/index.html
        dest: /var/lib/jenkins/templates/index.html
        owner: jenkins
        group: jenkins
        mode: '0644'
